# Generated by Django 3.1.1 on 2020-09-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
